package com.charusat.canteen.dto;

import java.util.List;

/**
 * Payment-related DTOs for Razorpay integration.
 * All amounts are in paise (smallest currency unit) — never floats.
 */
public class PaymentDTOs {

    // ──── Request DTOs ────────────────────────────────────

    public record CreatePaymentOrderRequest(
            Long amount,          // in paise (e.g., 10000 = ₹100)
            String currency,      // must be "INR"
            Long foodOrderId,     // linked food order
            String idempotencyKey // UUID generated by frontend
    ) {}

    public record VerifyPaymentRequest(
            String razorpayOrderId,
            String razorpayPaymentId,
            String razorpaySignature
    ) {}

    public record VpaValidationRequest(
            String vpa  // e.g., "user@okaxis"
    ) {}

    // ──── Response DTOs ───────────────────────────────────

    public record CreatePaymentOrderResponse(
            String razorpayOrderId,
            Long amount,
            String currency,
            String keyId  // NEVER the keySecret
    ) {}

    public record VerifyPaymentResponse(
            boolean verified,
            String orderId,
            String status,
            String message
    ) {}

    public record VpaValidationResponse(
            boolean valid,
            String name
    ) {}

    public record PaymentStatusResponse(
            String razorpayOrderId,
            String status,
            String razorpayPaymentId
    ) {}

    public record PaymentAnalyticsResponse(
            long totalRevenuePaise,
            long successfulPayments,
            long failedPayments,
            double upiPercentage,
            List<DailyRevenue> dailyRevenue
    ) {}

    public record DailyRevenue(
            String date,
            long amountPaise
    ) {}
}
